apiVersion: v1
kind: Service
metadata:
  name: hello-devops
  namespace: hello-devops
  labels:
    app: hello-devops
    # This label is needed by the ServiceMonitor selector
spec:
  selector:
    app: hello-devops
  ports:
  - name: http
    # The port name 'http' is referenced in the ServiceMonitor
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  type: NodePort

